name: fz_reactions_chat
description: "Reactions Chat Package"
repository: https://github.com/fadyZaherEng/fzReactionsChat
homepage: https://github.com/fadyZaherEng/fzReactionsChat
version: 0.0.1
environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:


